### ISSUE TITLE
install Problem

### ISSUE THREAD

**Issue by herbiro** [mumblebaj/MMM-Growatt#1]
hi, i think i'm to dump to install your Modul mmm-growatt.
it only show "undefinedW"
can you please help me?

follow steps i have done:
npm install growatt
and then i follow the MM install instuctions and fill the growatt login data an PlantID and so on. But it dont work. :-(

thank you verry much for your help and best greetings from germany

herbiro

**Comment by mumblebaj** [comment]
Hi. You need to go into the /MagicMirror/modules folder first and then run git clone https://github.com/mumblebaj/MMM-Growatt.git. When that is finished you need to go into the MMM-Growatt folder and run npm install.  When that is done you update the config/config.js file.

        {
                module: "MMM-Growatt",
                position: "middle_center",
                disabled: true,
                //        header: "My Plant Data",
                config: {
                        username: "yourusername",
                        password: "yourpassword",
                        plantId: yourplantid,
                        deviceSerial: "yourdeviceserial",
                        updateInterval: 1000*60*30
                }
        },

if you have done all the above steps correctly then it should work.

**Comment by herbiro** [comment]
This means i dont need to "npm install growatt" ?

**Comment by mumblebaj** [comment]
There is no such step. These are the only steps to get the module installed: Nowhere in those steps does it say npm install growatt.
![image](https://github.com/mumblebaj/MMM-Growatt/assets/39963138/04e2fba4-9e02-4318-b447-39ca1f043ec6)
