### ISSUE TITLE
Unsupported inverter

### ISSUE THREAD

**Issue by zephyr2206** [mumblebaj/MMM-Growatt#4]
0|mm       | [11.08.2023 11:20.31.408] [LOG]   Inverter not yet supported. Please log a call at module Github page, https://github.com/mumblebaj/MMM-Growatt/issues

I have a Growatt MID10KTL3-XL inverter.

**Comment by mumblebaj** [comment]
Hi Zephyr. As far as I can see from the growatt npm module it does not mention XL. If you can edit the node_helper.js file and add a console.log in the following position for me as highlighted in red. I need to get the data to see where it fits in.  If you can send me the info I can have a look for you.  I am going into hospital for an operation tomorrow and will look at it as soon as I am out. If you can send me the info today still I can see how much I can assist with today.

![image](https://github.com/mumblebaj/MMM-Growatt/assets/39963138/db52c5c8-3d99-4c50-9f04-1d5efa0d4ff6)

**Comment by mumblebaj** [comment]
Hi. I have added some debug stuff to the module. please do a git pull. In the config/config,js set debug to true for this module.

```
        {
                module: "MMM-Growatt",
                position: "middle_center",
                disabled: false,
                config: {
                        username: "username",
                        password: "password",
                        debug: false,
                        updateInterval: 1000*60*15,
                }
        },
```

Start MM. Give it a few minutes and then stop MM. In the MMM-Growatt folder, you will find a file called growatt.log.  Please send me the file and I will look at the data.

**Comment by zephyr2206** [comment]
Hi.

Sorry for not replying sooner. Lot of things happening here as well.
Hope the operation went well and that youre back on your feet soon.

Here are the log file you requested. No hurry so look at it when youre better.

[growatt.log](https://github.com/mumblebaj/MMM-Growatt/files/12329212/growatt.log)

Another thing. I have an on-grid inverter so no battery. Is it possible to remove it for this inverter?

**Comment by mumblebaj** [comment]
Hi. Just got home and have to off my feet for a few days. Working on this one will help me get through it. :-) 

You inverter type is "max" and max only gets totalData and historyLast. I need some screenshots of your growatt dashboard or if you don't mind sharing your creds with me to put it all together that would be better. You can mail me direct on bernardmumble@gmail.com and I can get onto it today.

**Comment by mumblebaj** [comment]
Hi. I have gone through the data and the code for the growatt npm module. It only caters for getting totalData and history data. The only data of use is Solar data that I can get from the data returned. I can unfortunately not build anything meaningful from this. I do not see anything for battery storage or load consumption or grid activity etc. from any of the data returned.

**Comment by zephyr2206** [comment]
Thats too bad. Thank you anyway for trying :D
