### ISSUE TITLE
Option to use the US Growatt server

### ISSUE THREAD

**Issue by ruralbrewer** [mumblebaj/MMM-Growatt#5]
I was having an issue getting this to work, and I noticed that your documentation says that you must have a server.growatt.com account. Mine is actually server-us.growatt.com. I didn't think it would make a difference, but it definitely does. I can't log into server.growatt.com. So then I started wondering if the us server would work the same, so I hard code the us address into the growatt module, and it worked just fine. 

Then I realized that the growatt module will take a server address as a config parameter. So I updated your code to send the us server when it creates the growatt api. This, of course, also worked. 

So then I created a const in your node_helper that has both servers, and added a "usServer: false" to your config defaults. Then I added a conditional to the `getGrowattData()` method to set one of the two servers based on that config setting. 
Doing all this allows a user to optionally choose the us server in the config, but locks down the choices to just the two. 

Given that it was recommended to me when I signed up for my Growatt account that I use the US server, it would be nice if you incorporated this option into your module. 

I pulled the code, and created a new branch to make the changes locally. I don't know if you want to take pull requests, but if you allowed me I could. Or I could just post the changes that I made, and you could paste them in. Or you could do your own version. It was pretty straight forward and simple. Just a thought.

**Comment by mumblebaj** [comment]
Hi Lee,

 

Thank you for using the module. Hope you are enjoying it.

 

You can submit a PR. I will review and merge once tested.

 

Thanks in advance for the addition. Much appreciated.

 

BM

 

From: Lee Wilkins ***@***.*** 
Sent: Wednesday, 30 August 2023 22:21
To: mumblebaj/MMM-Growatt
Cc: Subscribed
Subject: [mumblebaj/MMM-Growatt] Option to use the US Growatt server (Issue #5)

 

I was having an issue getting this to work, and I noticed that your documentation says that you must have a server.growatt.com account. Mine is actually server-us.growatt.com. I didn't think it would make a difference, but it definitely does. I can't log into server.growatt.com. So then I started wondering if the us server would work the same, so I hard code the us address into the growatt module, and it worked just fine.
Then I realized that the growatt module will take a server address as a config parameter. So I updated your code to send the us server when it creates the growatt api. This, of course, also worked.
So then I created a const in your node_helper that has both servers, and added a "usServer: false" to your config defaults. Then I added a conditional to the getGrowattData() method to set one of the two servers based on that config setting.
Doing all this allows a user to optionally choose the us server in the config, but locks down the choices the just the two.

Given that it was recommended to me when I signed up for my Growatt account, it would be nice if you incorporated this option into your module.

I pulled the code, and created a new branch to make the changes locally. I don't know if you want to take pull requests, but if you allowed me I could. Or I could just post the changes that I made, and you could paste them in. Or you could do your own version. Ir was pretty straight forward and simple. Just a thought.

**Comment by ruralbrewer** [comment]
I got permission denied. I think you have to add me as a collaborator before I can push. 
And yes, I am liking the module! Thank you.

**Comment by mumblebaj** [comment]
Hi Lee,

Apologies for the late response. Had a third operation this past weekend.  My module does not specify a server as the server is built into the growatt npmjs module. I am assuming that you may have made changes to that module hence not being able to submit a PR. Can you send me the changed that you made and I can have a look at it further and will request for the us server to be added as an option to the npmjs growatt module.

**Comment by ruralbrewer** [comment]
No worries. But this is definitely changes to your repo (not the growatt module). No one can push to your repo unless you add them as a collaborator. It's easy to do, but I understand if you don't want to do that. Below are the changes I made to MMM-Growatt:

First, I added a const object to hold the two servers. I added it above the "options" object on line 6 of `node_helper.js`:

```
const servers = {
  main: 'https://server.growatt.com',
  us: 'https://server-us.growatt.com'
}
```

And then on line 238 of the `node_helper.js` file (in `getGrowattData()`), I added a conditional based on the "payload" (config). And updated the line after it which creates the API:
```
    const server = payload.usServer ? servers.us : servers.main;
    const growatt = new api({server: server})
```
Then the only other thing that needed to be done was to add a new parameter to your config defaults (line 3 of `MMM-Growatt.js`). I called it "usServer":

```    
    defaults: {
        title: "MMM-Growatt",
        usServer: false,
        updateInterval: 1000*60*15,
        username: "username",
        password: "password",
        mode: "dual"
    },
```
It defaults to false, meaning that the main (server.growatt.com) server will be used. But if a user of your module adds `usServer: true` to their configuration, it will use the US server when creating the API. 

This is all based on the fact that the other module (growatt - the API) allows a server to be passed in. 

In my attempted PR, I also updated the documentation to reflect these changes, but I will let you decide on that. 

It works well for me. And would probably help out a lot of people going forward. Let me know if you have any questions.

**Comment by mumblebaj** [comment]
Hi Lee,

 

Yeah, it is in the constructor. I have made the changes to the code and will push a new version shortly.

**Comment by ruralbrewer** [comment]
That's great! Thank you.

**Comment by ruralbrewer** [comment]
I reset my local code and pulled the new update. All works as expected. Thanks again.

**Comment by mumblebaj** [comment]
Pleasure Lee and thanks for the suggestion.
